### ISSUE TITLE
missing step of "set contract"

### ISSUE THREAD

**Issue by chesterchen2010** [xJonathanLEI/eosyield#1]
It seems that the step of "cleos set contract yield ..." is missing in the readme.md, if I'm not mistaken. Between "newaccount" and "set account permission".

**Comment by xJonathanLEI** [comment]
Thank you. Problem fixed in commit [8e840c9cbd2a6e4c08ab28e1f1ac15e3ed47f8ae](https://github.com/xJonathanLEI/eosyield/commit/8e840c9cbd2a6e4c08ab28e1f1ac15e3ed47f8ae).
